### ISSUE TITLE
Image not found when running app second time

### ISSUE THREAD

**Issue by stantoncbradley** [applivery/applivery-ios-sdk#12]
App builds and runs fine on first build. After that I get this error:
```
dyld: Library not loaded: @rpath/Applivery.framework/Applivery
  Referenced from: /Users/xxxx/Library/Developer/CoreSimulator/Devices/2B958A94-5B82-4A05-89E9-E2321B56CDE6/data/Containers/Bundle/Application/E9923A17-F06D-46C9-B18A-1D255CA1F9D3/lcard_app.app/lcard_app
  Reason: image not found
```
Works fine after I clean the build, but then it takes forever to run the app again. Please help!

**Comment by Alesete** [comment]
Hi @stantoncbradley!

I can remember that you are using cocoapods finally, true? It seems to me that you didn’t remove the script for the appstore uploads (the one that erase the simulator slice).

With cocoapods the script is not needed because cocoapods compiles your dependencies along with your project and its configuration. When you run your project, the script is probably running and erasing the simulator slice, but when you clean the project all the cocoapods dependencies are cleaned as well and recompiled again.

Hope this can help you!

**Comment by stantoncbradley** [comment]
yup thought I removed that. thanks!
