### ISSUE TITLE
Neither 2.7 nor 2.7.2 will build in a React Native app with CocoaPods and XCode 10.2

### ISSUE THREAD

**Issue by driddle** [applivery/applivery-ios-sdk#18]
I got my employer set up with applivery, partly on the promise of using the SDK for OTA updates.

The mobile project I am trying to build uses CocoaPods, and all the other modules seem to be in Objective-C. 

As I cannot use the use_frameworks! statement in the podfile, I am using :modular_headers => true.

I have tried multiple permutations, and I cannot get this to build, which may be a dealbreaker in using your service...

**Comment by CesarTrigo** [comment]
Hi @driddle.
Our iSO team is taking a look into it. We will come back to you as soon as possible.
Best,
C.

**Comment by Alesete** [comment]
Hello @driddle , as I can read from CocoaPods docs, the use of `:modular_headers => true` is intended only for Objective-C static frameworks. Applivery is actually the oposite, is a Swift dynamic framework so it shouldn't use this attribute with the Applivery pod at all

Greetings and sorry for the delay.

**Comment by driddle** [comment]
Interesting, as that was supposed to be the replacement for the use_frameworks! statement.

The CocoaPods for the Expo/React Native build do not like the use_frameworks! statement, which it seems like the Applivery SDK requires?

**Comment by Alesete** [comment]
As I can read in some docs, since CocoaPods 1.5 the use_frameworks! statement is no longer needed. I suppose it should  removing it, but I can’t test it (i come back in a few days)

Meanwhile, if ewmoving that statement doesn’t works, a workaround could be integrate Applivery (and any other Swift framework) with carthage. So you can have your statics libs with CocoaPods and the dynamic ones with carthage.

Hope this helps, thanks and greetings!
