### ISSUE TITLE
Crash reporting

### ISSUE THREAD

**Issue by CesarTrigo** [applivery/applivery-ios-sdk#23]
To be defined soon...

Related roadmap issue: https://github.com/applivery/roadmap/issues/50

**Comment by nishiarya** [comment]
Applivery Team,
 
Thanks for selecting this major feature for development.
 
Just wanted to check with you for custom crash reporting feature with data or log attachment as Crash Reporting you will already target. Please also include some delegates to detect app crash on last session so that a custom log file or binary data should be send with crash report.
**Expected feature for Crash Reporting** 
1. Standard Crash Reporting
2. Custom Crash Reporting on first app launch after crash with log txt file or as binary data attachment. 
Sample Examples: 
A. Feature in HockeyApp
- (NSString *)applicationLogForCrashManager:(BITCrashManager *)crashManager
https://www.hockeyapp.net/help/sdk/ios/3.0.0/Protocols/BITCrashManagerDelegate.html#//api/name/applicationLogForCrashManager:
B. Feature in AppCenter
- (NSArray<MSErrorAttachmentLog *> *)attachmentsWithCrashes:(MSCrashes *)crashes forErrorReport:(MSErrorReport *)errorReport
https://docs.microsoft.com/en-us/appcenter/sdk/crashes/ios

Is there any expected dates of release including with Crash Reporting features?

**Comment by CesarTrigo** [comment]
Thank you for the feedback @nishiarya.
We are taking your comments into consideration for the upcoming releases.
We will keep you updated here about the progress.

Regards,
C.
