### ISSUE TITLE
iOS 13 modal present problems

### ISSUE THREAD

**Issue by RafaelFernandezAlv** [applivery/applivery-ios-sdk#29]
Hi,

I`m testing the SDK but I have a problem when show the feedback UI over iOS 13. Apple change the present type of screens to page sheet and this cause that the gesture of draw over the screenshot not work correctly, because the gesture of draw and close the screen is the same.

**Comment by CesarTrigo** [comment]
Hi Rafael,
Thank you for contacting. This issue has been already fixed in [v3.1](https://github.com/applivery/applivery-ios-sdk/releases/tag/v3.1) of the iOS SDK (released a few days ago), fixed through [this commit](https://github.com/applivery/applivery-ios-sdk/commit/6228e8229d01f92ba01030772850c0abeb443b5c) 

I'm assuming that you are importing the iOS SDK using Cocoapods, however we are still making v3.1 compatible with [Cococapods](https://cocoapods.org/) that now only support until [v3.0](https://cocoapods.org/pods/Applivery). We expect to have it available this week.

In the meantime you can import v3.1 by using [Carthage](https://github.com/applivery/applivery-ios-sdk#using-carthage).

I'll keep you updated and maintain this Issue Open until that moment.

**Comment by CesarTrigo** [comment]
Hi @RafaelFernandezAlv,
We have just released a new hotfix ([v3.1.1](https://github.com/applivery/applivery-ios-sdk/releases/tag/v3.1.1
)) that enables the latest version of the iOS SDK in [Cocoapods](https://cocoapods.org/pods/Applivery).
I will tentatively close the issue. Feel free to reopen it if you detect any issues.
Thank you,
C.
