### ISSUE TITLE
Remove support for appStoreRelease

### ISSUE THREAD

**Issue by CesarTrigo** [applivery/applivery-ios-sdk#37]
**Is your feature request related to a problem? Please describe.**
Some companies are reporting issues while uploading Apple App Store with the Applivery SDK integrated (even when it's disabled using the `appStoreRelease=true`)

**Describe the solution you'd like**
We will be removing support for `appStoreRelease` feature.
We will highly recommend conditionally exclude the Applivery SDK for builds that will be published  in the Apple App Store.

**Comment by iniprocjoe** [comment]
I noticed issues with appStoreRelease=true as well, but I would really like to disable the Applivery popup from appearing on launch.  As far as I could tell, this was the only way to do that without modifying the source.

**Comment by CesarTrigo** [comment]
Hi @iniprocjoe 
You can disable the Automatic Updates feature from the **Settings > SDK > Automatic updates** section.
<img width="1126" alt="sdk" src="https://user-images.githubusercontent.com/453657/122541358-d6bed800-d029-11eb-8dfd-c8f3911a664c.png">

Once disabled, the pop-up should never appear again.
You can also read [here](https://www.applivery.com/docs/troubleshooting/exclude-applivery-ios-sdk/) about how to conditionally excluding Applivery iOS SDK based on the Environment.

Hope this helps.

Best regards,
C.

**Comment by iniprocjoe** [comment]
Thanks for the rapid response, @CesarTrigo ! You're right. Disabling Automatic updates does solve the problem on iOS. Unfortunately, my problem is a bit more involved than that. My company has both an Android and an iOS build that use Applivery's SDKs, and release versions of both platforms are bundled under the same App on Applivery's server. Disabling Automatic updates on iOS also disables them on Android and we want them on Android. 

### A little bit about my project...
We are working in a Xamarin environment. Using Applivery's SDKs as a base, I've built binding libraries for both platforms. I have a custom UI component for the updates that I developed to give the user the same look and feel across both platforms. That part all works well. 

### Here is the problem... 
**In the Android SDK, a call to Applivery.IsUpToDate(callback) seems to only return false if Automatic updates is true. I believe this is a separate bug.** We need the callback to return 'false' to display our custom popup, so if we disable Automatic updates for the app, our Android product will never see a popup to update the app! On iOS, instead of a callback, there is a property called Applivery.IsUpToDate and it seems to return the correct value regardless of the Automatic updates value.

I was thinking the easiest way to design the SDK into both of our apps would be to enable Automatic Updates on the server and disable the iOS UI component by setting appStoreRelease=true.  With iOS, Applivery.IsUpToDate performs brilliantly and we can use it to launch our custom popup at both launch and on resume from sleep. However, on iOS we see 2 popups on launch, Applivery's and our own. Technically the iOS Applivery popup doesn't even display on the first launch. It only displays on the 2nd or later launch. I'm guessing the SDK's writing something to non-volatile memory during the first launch. Anyway, I figured this popup rendering was associated with this issue #37. I am a bit disheartened to see the feature go because it would be easy to solve my problem if I could just disable the iOS SDK-generated popup.

**Comment by CesarTrigo** [comment]
Hi @iniprocjoe, thank you for the accurate description.
After some internal discussions, the team is working on solving this Android SDK issue you are describing at the very beginning of you message so that you can disable the automatic updates and programmatically. We are also working on updating the iOS SDK to return a callback instad.

**Comment by CesarTrigo** [comment]
I'm closing this issue in favor of #39 .

**Comment by iniprocjoe** [comment]
Thanks @CesarTrigo !
